# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    environment:
      HUB_RELEASE: "https://github.com/github/hub/releases/download/v2.11.2/hub-linux-amd64-2.11.2.tgz"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: Install dependencies
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: Building workflow
          command: |
            mkdir generated workflow
            cp -r icon.png info.plist src/* workflow
            . venv/bin/activate
            python workflow-build.py -o generated workflow

        run:
          name: Creating GitHub Release
          command: |
            mkdir bin
            # https://snippets.cacher.io/snippet/f1eb452be2d3fe7c9d51
            BIN_PATH="$(basename $HUB_RELEASE .tgz)/bin/hub"
            curl -fsSL $HUB_RELEASE | tar xzf - -C bin --transform="s,$(dirname $BIN_PATH)/,," $BIN_PATH
            bin/hub release create -a generated/*.alfredworkflow -m "Release ${CIRCLE_TAG}" "${CIRCLE_TAG}"

      - store_artifacts:
          path: generated
          destination: workflow

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
