name: labeler

on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Pull Request size labeler
        uses: CodelyTV/pr-size-labeler@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
