name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build package
        id: build_package
        run: |
          poetry build
          echo "::set-output name=file::$(ls dist/*.tar.gz)"

      # - name: Publish to PyPI
        # run: poetry publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PASS }}

      - name: Archive package
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ${{ steps.build_package.outputs.file }}

  release:
    runs-on: ubuntu-latest

    needs: publish

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Download package
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Create brew package
        run: scripts/create_brew_package.py $(ls dist/*.tar.gz)

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: $(ls dist/*-brew.tar.gz)
          asset_content_type: application/gzip
