name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Alfred workflow
        id: builder
        uses: almibarss/build-alfred-workflow@79a9b4559553003d019a5b31750237682c307d57
        with:
          workflow_dir: .
          exclude_patterns: .git/* .github/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.builder.outputs.workflow_file }}
