---
name: test-workflow-2

on:
  issue_comment:
    types: [created, edited]

jobs:
  integration:
    name: Pass PR check
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/test-qa --kind integration')
    steps:
      - name: Label PR
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload);
            const repo = {
              owner: "almibarss",
              repo: context.payload.repository.name
            }
            const {data: { workflow_runs }} = await github.rest.actions.listWorkflowRunsForRepo({ ...repo })
            const last_run = workflow_runs
              .find((r) => r.name === "Test workflow no. 2"
            && r.pull_requests.find((p) => p.number === context.payload.issue.number))
            if (last_run.conclusion === "failure") {
              await github.request('POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun', {
                ...repo,
                run_id: last_run.id
              })
            }

