---
name: Edited PR (feature)

on: [pull_request]

jobs:
  label:
    name: Remove label
    runs-on: ubuntu-latest
    steps:
      - name: Find last IT run
        uses: actions/github-script@v5
        with:
          script: |
            console.log(context);
            github.rest.issues.removeLabel({
                        issue_number: context.payload.issue.number,
                        owner: context.payload.repository.owner.login,
                        repo: context.payload.repository.name,
                        name: "my-label"
                      });

  label2:
    name: Fail check
    runs-on: ubuntu-latest
    steps:
      - name: Find last IT run
        uses: actions/github-script@v5
        with:
          script: |
            console.log(context);
